version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 ./main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server:/echoserver      
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BETTOR_NOMBRE=Julio
      - CLI_BETTOR_APELLIDO=Cortazar
      - CLI_BETTOR_DOCUMENTO=52820003
      - CLI_BETTOR_NACIMIENTO=1999-03-17
      - CLI_BETTOR_NUMERO=7542      
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client:/echoclient
      
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BETTOR_NOMBRE=Julio
      - CLI_BETTOR_APELLIDO=Cortazar
      - CLI_BETTOR_DOCUMENTO=52820003
      - CLI_BETTOR_NACIMIENTO=1999-03-17
      - CLI_BETTOR_NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client:/echoclient

  nctest:
    container_name: nctest
    build:
      context: .
      dockerfile: scripts/Dockerfile
    environment:
      - SERVER_PORT=12345
    networks:
      - testing_net
    volumes:
      - ./scripts:/scripts
    depends_on:
      - server
    command: ./nc_test.sh
      
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
