name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 ./main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server:/echoserver
    networks:
      - testing_net

  nctest:
    container_name: nctest
    build:
      context: .
      dockerfile: Dockerfile_nc
    environment:
      - SERVER_PORT=12345
    networks:
      - testing_net
    volumes:
      - ./:/scripts
    depends_on:
      - server
    command: ./validar-echo-server.sh

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
